### ISSUE TITLE
Your editor resources end up in game builds

### ISSUE THREAD

**Issue by XtroTheArctic** [Fydar/AssetIcons#46]
Hello.

Since you keep some icon files in Editor\Resources folder, these files end up in Game builds because Unity includes all assets in Resources folders without a reference check.

3rd party tools should not include a Resources folder for editor-only files such as UI icons.

Here is the screenshot of a built-assets analysis which shows that your editor related icons end up in the Game build.

![image](https://user-images.githubusercontent.com/6631429/147608223-991b9d65-a1d4-4637-ac88-f01724d1d11a.png)

**Comment by Fydar** [comment]
According to Unity's documentation on the subject:

> If the Resources folder is an Editor subfolder, the Assets in it are loadable from Editor scripts, but are removed from builds.

Source: https://docs.unity3d.com/Manual/SpecialFolders.html

I know that Unity outputs a list of all resources that it actually includes in builds during the build to a log file. This is the most effective way of actually determining whether a resource is included in the build or not.

It may be that the 3rd party tool is incorrectly reporting that my assets are being included in the build, or Unity's documentation doesn't reflect reality (not the first time that's happened).

**Comment by XtroTheArctic** [comment]
Yes. I checked the build log and saw that resource files in Editor folders aren't included in the build. Thank you for the info.

Btw, my screenshot is not from a 3rd party, it's from official Addressables package from Unity.

I'll report a bug to Unity.

Thank you.
